# Base image
FROM python:3.9-slim

# ✅ Establecer el directorio de trabajo
WORKDIR /app

# ✅ Copiar el archivo de dependencias
COPY requirements.txt .

# ✅ Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# ✅ Copiar el script de entrenamiento
COPY train.py .

# ✅ Ejecutar el script de entrenamiento
CMD ["python", "train.py"]
