FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY wait-for-model.py .

EXPOSE 8080

CMD ["sh", "-c", "python wait-for-model.py && python server.py"]
